### ISSUE TITLE
Publish via Maven Central

### ISSUE THREAD

**Issue by rhwood** [andrewrapp/xbee-api#2]
Can you please publish this via [Maven Central](http://search.maven.org)? It would make it significantly easier for maven-projects to depend on this library.

**Comment by andrewrapp** [comment]
In Maven now. BTW, it's a real convoluted process to get artifacts into maven central, which I'm sure scares off some devs. All the guides I found were inaccurate

https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.rapplogic%22
