### ISSUE TITLE
More of a question - Can you run the listener and send data at the same time

### ISSUE THREAD

**Issue by SkyMoCo** [andrewrapp/xbee-api#3]
I have a program that needs to read and write to multiple remote XBee's.   If I startup a listener, can I also have a thread that writes to remote XBee's or should one thread do all the reading and writing?

**Comment by andrewrapp** [comment]
sure, when you add a listener, it's the xbee library thread that is going to invoke your code when packets arrive, so your main thread is free to send packets or do whatever
