### ISSUE TITLE
maven compile issue

### ISSUE THREAD

**Issue by gokul96** [andrewrapp/xbee-api#4]
compiling on spring[STS IDE], attempting compile for raspberry pi 3 B armhf

[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.1:revision (get-the-git-infos) on project xbee-api: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by andrewrapp** [comment]
Looks like your .git directory is missing. If you clone the project from github you should have a .git. Alternatively, you could just disable the plugin
