### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by Thangarasu-hithub** [andrewrapp/xbee-api#5]
While compiling I am getting  "The system cannot find the file specified"  error,

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project xbee-api: Unable to execute gpg command: Error while executing process. Cannot run program "gpg.exe": CreateProcess error=2, The system cannot find the file specified -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by andrewrapp** [comment]
I moved the gpg plugin to the deploy phase so mvn package / install should be fine

**Comment by Thangarasu-hithub** [comment]
In pom.xml which plugin I have to remove.

**Comment by Thangarasu-hithub** [comment]
Project 'xbee-api' is missing required library: 'lib/log4j.jar'	xbee-api
Project 'xbee-api' is missing required library: 'lib/RXTXcomm.jar'	xbee-api
The project cannot be built until build path errors are resolved

I am getting this error. 
we have maven dependency for these library, even though I am getting this error. could you guide me to resolve this. I am using STS ide.

**Comment by andrewrapp** [comment]
Delete .project and .classpath files. I removed them from git so you can pull to remove

**Comment by Thangarasu-hithub** [comment]
Hi Andrewrapp,

Finally I am able to create jar file by using your application, Thanks for your support.
